version: "3.8"

services:
  backend:
    container_name: status_backend
    build: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "3001:3001"
    env_file:
      - .env
    command: npm run dev

  frontend:
    container_name: status_frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
